version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_v_latest
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    container_name: frontend_v_latest
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
